source "https://rubygems.org"

gem "haml"
gem "pg"
gem "redcarpet"
gem "redis"
gem "sinatra"
gem "sinatra-contrib"

group :development do
  gem "byebug"
  gem "shotgun"
end

group :production do
  gem "puma"
  gem "rack-json-logs"
end
